#:kivy 2.0.0
#:import dp kivy.metrics.dp

<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)

        Label:
            text: "Main Screen"
            font_size: "24sp"

        Button:
            text: "Log workout"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "workout_log"
                root.manager.transition.direction = "left"

        Button:
            text: "Check History"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "history_view"
                root.manager.transition.direction = "left"

<WorkoutLogView>:
    date_label: date_label
    BoxLayout:
        orientation: "vertical"
        spacing: dp(10)
        padding: dp(5)

        BoxLayout:
            orientation: "horizontal"
            spacing: dp(10)
            
            MDButton:
                pos_hint: {'center_x': .5, 'center_y': .5}
                on_press: 
                    app.root.current = "main"
                    root.manager.transition.direction = "right"

                MDButtonText:
                    text: "Go Back"

            MDButton:
                pos_hint: {'center_x': .5, 'center_y': .5}
                on_release: root.show_date_picker()

                MDButtonText:
                    text: "Open calendar"

        Label:
            id: date_label
            text: "Log Workout"
            font_size: "24sp"
            
        RecycleView:
            size_hint: 1.0,1.0

            BoxLayout:
                id: workout_entry_box
                orientation: 'vertical'        

<HistoryView>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)

        Label:
            text: "History view"
            font_size: "24sp"

        Button:
            text: "Go Back"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "main"
                root.manager.transition.direction = "right"

# The root widget
ScreenManager:
    id: screen_manager

    MainScreen:
        id: main_screen
        name: "main"
        manager: screen_manager
    WorkoutLogView:
        id: workout_log
        name: "workout_log"
        manager: screen_manager
    HistoryView:
        id: history_view
        name: "history_view"
        manager: screen_manager
