#:kivy 2.0.0
#:import dp kivy.metrics.dp

<MainScreen>:
    name: "main"
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)

        Label:
            text: "Main Screen"
            font_size: "24sp"

        Button:
            text: "Log workout"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "workout_log"
                root.manager.transition.direction = "left"

        Button:
            text: "Check History"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "history_view"
                root.manager.transition.direction = "left"

<WorkoutLogView>:
    name: "workout_log"
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)

        Label:
            text: "Log Workout"
            font_size: "24sp"
        MDButton:
            pos_hint: {'center_x': .5, 'center_y': .5}
            on_release: root.show_date_picker()

            MDButtonText:
                text: "Open calendar"

        Button:
            text: "Go Back"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "main"
                root.manager.transition.direction = "right"

<HistoryView>:
    name: "history_view"
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)

        Label:
            text: "History view"
            font_size: "24sp"

        Button:
            text: "Go Back"
            size_hint_y: None
            height: dp(48)
            on_press: 
                app.root.current = "main"
                root.manager.transition.direction = "right"

# The root widget
ScreenManager:
    MainScreen:
    WorkoutLogView:
    HistoryView: