<HistoryView>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(10)

        Label:
            text: "History view"
            font_size: "24sp"

        Button:
            text: "Go Back"
            size_hint_y: None
            height: dp(48)
            on_press:
                app.root.ids.screen_manager.current = "main"
                app.root.ids.screen_manager.transition.direction = "right"
