<WorkoutLogView>:
    date_label: date_label
    BoxLayout:
        orientation: "vertical"
        spacing: dp(10)
        padding: dp(5)

        BoxLayout:
            orientation: "horizontal"
            spacing: dp(10)

            MDButton:
                pos_hint: {'center_x': .5, 'center_y': .5}
                on_press:
                    app.root.ids.screen_manager.current = "main"
                    app.root.ids.screen_manager.transition.direction = "right"

                MDButtonText:
                    text: "Go Back"

            MDButton:
                pos_hint: {'center_x': .5, 'center_y': .5}
                on_release: root.show_date_picker()

                MDButtonText:
                    text: "Open calendar"

        Label:
            id: date_label
            text: "Log Workout"
            font_size: "24sp"

        RecycleView:
            size_hint: 1.0,1.0

            BoxLayout:
                id: workout_entry_box
                orientation: 'vertical'
